### PR TITLE
Dev branch

### PR DESCRIPTION
**Pull request by addod19**
# Milestone1: Project Setup

This project is setup with two directories:

- `lib` - for the game logic
- `bin` - for the executable file main.rb

### CODE REVIEW

**Review by maelfosso — CHANGES_REQUESTED** [review]
Hello @addod19 & @maya88en 

Thanks for this good job :smile: 
There are still a few things to do

- [ ] Please setup a code linter. Follow that [link](https://github.com/microverseinc/linters-config/tree/master/ruby) to do it

- [ ] Follow the Git Flow. You had to create a branch according to the instructions described below:
- You create a `dev_branch` branch from the `master`
- Then you create a `milestone_1` branch from the `dev_branch`
- Then you ask a REVIEW for a PR to merge `milestone_1` into `dev_branch`

Read the [pathwrigth](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/) for more information about what you be done.

Please, kindly make the changes and submit a new code review request.
Thanks

**Review by bellom — CHANGES_REQUESTED** [review]
Hi Team, 
Great job :+1:  setting up the project but we still need to work on it. :slightly_smiling_face: 
**You need to make changes according to the previous review.**

**Just few things to do before moving on to the next milestone...**
1. Always read the pathwright instructions before starting the project to avoid the need of sending another code review, according to the pathwright you are to use `Git Flow` not `GitHub Flow`, make sure to use 'Git Flow' in the next milestone.
Short Explanation Hint: 
`GitHub Flow`: Pull Requests is raise from feature branches to the master.
`Git Flow`: Pull Requests is raise from feature branches to the development.
2. Add linter's check and fix all errors if need too, checkout this [linters-config#troubleshooting](https://github.com/microverseinc/linters-config#troubleshooting) for help. Example below;
image
If you are not having this check on your `Github` page, kindly visit :point_right:[ linter set up](https://github.com/microverseinc/linters-config/blob/master/ruby/.stickler.yml)

Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Comment by addod19** [comment]
@bellom does it mean that, i will send a PR from the feature branch(project_setup) and not the dev_branch ? Git flow. Should i send a PR from the project_setup ie feature branch?
What we did was after writing code, we merged the feature branch(project_setup) to the dev_branch before making PR.
we have config linters but how do i check if its configured?

**Review by maelfosso — APPROVED** [review]
Hello @addod19 @maya88en 

The next please, don't merge any branch into the `master` branch unless all the milestone has been approved.
For the next milestone, create a branch (`milestone_2` for example) from your current `dev_branch`
After working on the milestone 2, **don't merge it into the `dev_branch` as you did with the milestone 1**, just create a PR for merging `milestone 2 branch` into the `dev_branch` and then request a code review request with that PR. If it's approved you will do the merge and as the `dev_branch` will have the update from `milestone 2 branch`, you will create `milestone 3 branch` from the `dev_branch` and so on.

I hope it's clearer now.

# Good job :+1:  :smile: 

You can merge and fill the milestone completion form.
Good luck with the next step

**Pull request merged**
